# Generated by Django 4.0.1 on 2023-02-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoid', models.IntegerField()),
                ('ql', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('slot', models.CharField(max_length=32)),
                ('reqs', models.JSONField()),
                ('effects', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Pocketboss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('level', models.IntegerField()),
                ('playfield', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=265)),
                ('mobs', models.CharField(max_length=256)),
                ('drops', models.ManyToManyField(related_name='dropped_by', to='tinkerpocket.Symbiant')),
            ],
        ),
    ]
