# Generated by Django 4.0.1 on 2023-02-15 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkerpocket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbiant',
            name='family',
            field=models.CharField(default=None, max_length=32),
            preserve_default=False,
        ),
    ]
