# Generated by Django 4.0.1 on 2022-01-09 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ql', models.IntegerField()),
                ('clusterslot', models.CharField(max_length=16)),
                ('impslot', models.IntegerField()),
                ('skill', models.CharField(max_length=32)),
                ('jobeskill', models.CharField(max_length=32)),
                ('npmod', models.FloatField()),
                ('jobemod', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Implant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoid', models.IntegerField()),
                ('metatype', models.CharField(max_length=1)),
                ('name', models.CharField(max_length=256)),
                ('ql', models.IntegerField()),
                ('type', models.IntegerField()),
                ('slot', models.IntegerField()),
                ('icon', models.IntegerField()),
                ('reqs', models.JSONField()),
                ('bright', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bright', to='tinkerplants.cluster')),
                ('faded', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faded', to='tinkerplants.cluster')),
                ('shiny', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shiny', to='tinkerplants.cluster')),
            ],
        ),
    ]
