# Generated by Django 4.0.1 on 2022-01-09 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkerplants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='implant',
            name='metatype',
        ),
        migrations.AddField(
            model_name='cluster',
            name='hival',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cluster',
            name='loval',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='cluster',
            name='clusterslot',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='implant',
            name='bright',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='implant',
            name='faded',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='implant',
            name='shiny',
            field=models.CharField(max_length=32),
        ),
    ]
