# Generated by Django 4.2.6 on 2024-01-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoid', models.IntegerField()),
                ('name', models.CharField(max_length=128)),
                ('icon', models.CharField(max_length=12)),
                ('school', models.CharField(max_length=24)),
                ('strain', models.IntegerField()),
                ('strain_name', models.CharField(max_length=32)),
                ('profession', models.IntegerField(default=0)),
                ('location', models.CharField(max_length=256)),
                ('ql', models.IntegerField(default=1)),
                ('spec', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('expansion', models.IntegerField(default=0)),
                ('uploaded_by', models.JSONField(default=list)),
                ('mm', models.IntegerField(default=0)),
                ('bm', models.IntegerField(default=0)),
                ('mc', models.IntegerField(default=0)),
                ('ts', models.IntegerField(default=0)),
                ('pm', models.IntegerField(default=0)),
                ('si', models.IntegerField(default=0)),
            ],
        ),
    ]
