# Generated by Django 4.2.6 on 2024-01-14 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkernanos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nano',
            name='fp_able',
            field=models.BooleanField(default=False),
        ),
    ]
