# Generated by Django 4.2.6 on 2024-01-14 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinkernanos', '0002_nano_fp_able'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nano',
            name='uploaded_by',
        ),
    ]
