# Generated by Django 4.2.6 on 2024-01-14 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkernanos', '0003_remove_nano_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nano',
            name='strain_name',
            field=models.CharField(max_length=64),
        ),
    ]
