# Generated by Django 4.2.6 on 2024-01-14 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkernanos', '0004_alter_nano_strain_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nano',
            name='nanodeck',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='nano',
            name='profession'
        ),
        migrations.AddField(
            model_name='nano',
            name='profession',
            field=models.JSONField(default=list),
        ),
    ]
