PROFESSIONS = {
    '0' : 'Adventurer',
    '1' : 'Agent',
    '2' : 'Bureaucrat',
    '3' : 'Doctor',
    '4' : 'Enforcer',
    '5' : 'Engineer',
    '6' : 'Fixer',
    '7' : 'Keeper',
    '8' : 'Martial Artist',
    '9' : 'Meta-Physicist',
    '10' : 'Nano-Technician',
    '11' : 'Shade',
    '12' : 'Soldier',
    '13' : 'Trader',
}

def initial_weapons():
    return {
        'breed' : 0, 
        'profession' : 0,
        'level' : 1,
        '1hb' : 1,
        '1he' : 1,
        '2hb' : 1,
        '2he' : 1,
        'martial_arts' : 1,
        'melee_energy' : 1,
        'piercing' : 1,
        'assault_rifle' : 1,
        'bow' : 1,
        'mg_smg' : 1,
        'pistol' : 1,
        're' : 1,
        'rifle' : 1,
        'shotgun' : 1,
        'aimed' : 1,
        'brawl' : 1,
        'burst' : 1,
        'dimach' : 1,
        'fastattack' : 1,
        'fling' : 1,
        'fullauto' : 1,
        'sneak' : 1,
        'melee_init' : 1,
        'phys_init' : 1,
        'ranged_init' : 1,
        'aggdef' : 1,
        'aao' : 0,
        'add_dmg' : 0,
        'target_ac' : 1,
        'dmg_type' : 0,
    }