# Generated by Django 4.2.6 on 2024-03-01 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkertools', '0002_alter_action_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncriterion',
            name='order',
            field=models.IntegerField(null=True),
        ),
    ]
