# Generated by Django 4.2.6 on 2024-03-01 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tinkertools', '0003_alter_actioncriterion_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncriterion',
            name='action',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tinkertools.action'),
        ),
        migrations.AlterField(
            model_name='actioncriterion',
            name='criterion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tinkertools.criterion'),
        ),
    ]
