# Generated by Django 4.2.6 on 2024-03-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkertools', '0004_alter_actioncriterion_action_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='aoid',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shophash',
            name='baseAmount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shophash',
            name='maxLevel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shophash',
            name='minLevel',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shophash',
            name='regenAmount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shophash',
            name='regenInterval',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shophash',
            name='spawnChance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='spellID',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='target',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='tickCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spell',
            name='tickInterval',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='spelldata',
            name='event',
            field=models.IntegerField(null=True),
        ),
    ]
