# Generated by Django 4.2.6 on 2024-03-02 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkertools', '0005_alter_item_aoid_alter_shophash_baseamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemClass',
            field=models.IntegerField(null=True),
        ),
    ]
