# Generated by Django 4.2.6 on 2024-03-09 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkertools', '0006_item_itemclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='ql',
            field=models.IntegerField(null=True),
        ),
    ]
