# Generated by Django 4.0.1 on 2023-01-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aoid', models.IntegerField()),
                ('ql', models.IntegerField()),
                ('name', models.CharField(max_length=256)),
                ('atk_time', models.IntegerField()),
                ('rech_time', models.IntegerField()),
                ('dmg_min', models.IntegerField()),
                ('dmg_max', models.IntegerField()),
                ('dmg_crit', models.IntegerField()),
                ('clipsize', models.IntegerField()),
                ('props', models.JSONField()),
                ('reqs', models.JSONField()),
                ('atk_skills', models.JSONField()),
                ('other', models.JSONField()),
            ],
        ),
    ]
