# Generated by Django 4.0.1 on 2023-02-07 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkerfite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weapon',
            name='dmg_type',
            field=models.IntegerField(default=0),
        ),
    ]
