# Generated by Django 4.0.1 on 2023-02-08 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkerfite', '0002_weapon_dmg_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weapon',
            name='dmg_type',
            field=models.IntegerField(),
        ),
    ]
