# Generated by Django 4.0.1 on 2022-02-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('ql', models.IntegerField()),
                ('mc', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('recharge', models.IntegerField(default=0)),
                ('cost', models.IntegerField()),
                ('low_dmg', models.IntegerField()),
                ('high_dmg', models.IntegerField()),
                ('ac', models.CharField(max_length=32)),
                ('nr_pct', models.IntegerField()),
                ('atk_cap', models.IntegerField()),
            ],
        ),
    ]
