# Generated by Django 4.0.1 on 2022-03-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkernukes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nano',
            name='deck',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nano',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nano',
            name='spec',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nano',
            name='atk_cap',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='nano',
            name='nr_pct',
            field=models.IntegerField(default=0),
        ),
    ]
