# Generated by Django 4.0.1 on 2023-01-12 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tinkernukes', '0002_nano_deck_nano_level_nano_spec_alter_nano_atk_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nano',
            name='dot_delay',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nano',
            name='dot_hits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nano',
            name='nt_dot',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nano',
            name='strain_cd',
            field=models.IntegerField(default=0),
        ),
    ]
