# Generated by Django 4.2.6 on 2024-01-10 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tinkernukes', '0003_nano_dot_delay_nano_dot_hits_nano_nt_dot_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Nano',
            new_name='Nuke',
        ),
    ]
